# Generated by Django 3.2.18 on 2023-04-14 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcallback',
            old_name='user_element',
            new_name='user_elements',
        ),
        migrations.RenameField(
            model_name='requestcallback',
            old_name='user_mail',
            new_name='user_mails',
        ),
        migrations.RenameField(
            model_name='requestcallback',
            old_name='user_message',
            new_name='user_messages',
        ),
        migrations.RenameField(
            model_name='requestcallback',
            old_name='user_name',
            new_name='user_names',
        ),
        migrations.RenameField(
            model_name='requestcallback',
            old_name='user_number',
            new_name='user_numbers',
        ),
    ]
