# Generated by Django 3.2.18 on 2023-04-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0002_auto_20230414_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.TextField()),
            ],
        ),
    ]
